#!/bin/sh

# Default wallpaper directory
WALLPAPER_DIR="${HOME}/media/wallpapers/"

# Parse options
while getopts "s:" opt; do
	case $opt in
		s) FIRST_WALLPAPER="$OPTARG" ;;
		*) echo "Usage: $0 [-s wallpaper_path]"; exit 1 ;;
	esac
done

# Find wallpapers and shuffle
wallpapers=$(find "$WALLPAPER_DIR" -type f -printf '%P\n' | shuf --random-source=/dev/urandom)
trap 'kill $!' USR1
trap 'kill $!; RELOAD_WALL=y' USR2
trap 'kill $BG_PID $!' EXIT

if [ -z "${wallpapers}" ]; then
	exit 1
fi

if [ -n "${FIRST_WALLPAPER}" ]; then
	swaybg --mode fill -i "${FIRST_WALLPAPER}" &
	BG_PID=$!
	sleep 300 &
	wait $!
	kill "$BG_PID"
	# shellcheck disable=SC2154
	if [ "${RELOAD_WALL}" = "y" ]; then
		unset RELOAD_WALL
		break
	fi
fi

while true; do
	for wallpaper in ${wallpapers}; do
		swaybg --mode fill -i "${WALLPAPER_DIR}/${wallpaper}" &
		BG_PID=$!
		sleep 300 &
		wait $!
		kill "$BG_PID"
		# shellcheck disable=SC2154
		if [ "${RELOAD_WALL}" = "y" ]; then
			unset RELOAD_WALL
			break
		fi
	done
	wallpapers=$(find "${WALLPAPER_DIR}" -type f -printf '%P\n' | shuf --random-source=/dev/urandom)
done
