#!/bin/sh
# shellcheck disable=SC2154

# Default wallpaper directory
WALLPAPER_DIR="${HOME}/media/wallpapers/"

# Parse options
while getopts "s:" opt; do
	case ${opt} in
	s) FIRST_WALLPAPER="${OPTARG}" ;;
	*)
		echo "Usage: $0 [-s wallpaper_path]"
		exit 1
		;;
	esac
done

# Find wallpapers and shuffle
trap ':' USR1
trap 'kill ${OLD_OLD_PID} ${OLD_PID} ${NEW_PID}; RELOAD_WALL=y' USR2
trap 'kill ${OLD_OLD_PID} ${OLD_PID} ${NEW_PID}' EXIT

wallpapers=$(find "${WALLPAPER_DIR}" -type f -printf '%P\n' | shuf --random-source=/dev/urandom)
while [ -z "${wallpapers}" ]; do
	sleep 5
	wallpapers=$(find "${WALLPAPER_DIR}" -type f -printf '%P\n' | shuf --random-source=/dev/urandom)
done

if [ -n "${FIRST_WALLPAPER}" ]; then
	swaybg --mode fill -i "${FIRST_WALLPAPER}" &
	OLD_PID=$!
fi

while :; do
	for wallpaper in ${wallpapers}; do
		swaybg --mode fill -i "${WALLPAPER_DIR}/${wallpaper}" &
		NEW_PID=$!
		[ -n "${OLD_OLD_PID}" ] && kill "${OLD_OLD_PID}"
		OLD_OLD_PID="${OLD_PID}"
		OLD_PID="${NEW_PID}"
		sleep 300 &
		wait $!
		if [ "${RELOAD_WALL}" = "y" ]; then
			unset RELOAD_WALL
			break
		fi
	done
	wallpapers=$(find "${WALLPAPER_DIR}" -type f -printf '%P\n' | shuf --random-source=/dev/urandom)
done
