export DISPLAY=:0

. "${HOME}/.config/env"
/usr/bin/X -nolisten tcp :0 vt1 -keeptty &
sleep 2
xset +fp "${HOME}/.local/share/fonts/"
xset fp rehash

"${HOME}/.config/X11/dyn-wallpapers" -s "${HOME}/media/wallpapers/landscape.jpg" &
"${HOME}/.config/X11/dyn-status" &
"${HOME}/.config/X11/monitors"

xwallpaper --zoom "${HOME}/media/wallpapers/landscape.jpg"

# Composer
compton &

(
	sleep 3
	DISPLAY=:0 xmodmap "${HOME}/.config/X11/xmodmap"
) &

exec dwm
