#!/usr/bin/env sh

build_neovim() {
	DIR="$(pwd)"
	sudo apt-get update >/dev/null 2>&1 &&
		sudo apt-get upgrade -y >/dev/null 2>&1 &&
		sudo apt-get install ninja-build gettext cmake unzip curl build-essential -y >/dev/null 2>&1 &&
		curl -Ls "https://github.com/neovim/neovim/archive/refs/tags/stable.tar.gz" |
		tar -xC /dev/shm &&
		cd /dev/shm/neovim-stable && make CMAKE_BUILD_TYPE=RelWithDebInfo &&
		echo "Building Neovim" &&
		cd build && cpack -G DEB && sudo rm /usr/share/applications/nvim.desktop &&
		sudo apt install ./nvim-linux64.deb -y &&
		apt-cache depends neovim | awk '/Depends:/ {print $2}' | xargs sudo apt-get install -y &&
		echo "Installed Neovim" &&
		cd "${DIR}" && rm -rf /dev/shm/neovim-stable
}

down_neovim() {
	mkdir -p "${HOME}/.local/bin" "${HOME}/.local/share"
	curl -Ls "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz" -o /tmp/nvim-linux64.tar.gz &&
		curl -Ls "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz.sha256sum" -o /tmp/sha256sum &&
		(cd /tmp && sha256sum -c sha256sum) &&
		rm -rf "${HOME}/.local/share/nvim" "${HOME}/.local/bin/nvim" &&
		tar -xzf /tmp/nvim-linux64.tar.gz --transform 's/^nvim-linux64/nvim/' -C "${HOME}/.local/share" &&
		ln -s "${HOME}/.local/share/nvim/bin/nvim" "${HOME}/.local/bin/nvim" &&
		echo "Neovim updated successfully."
	rm -f /tmp/nvim-linux64.tar.gz /tmp/sha256sum
}
