#!/bin/sh
# shellcheck disable=SC2154

while getopts "s:" opt; do
	case ${opt} in
	s) FIRST_WALLPAPER="${OPTARG}" ;;
	*)
		echo "Usage: $0 [-s wallpaper_path]"
		exit 1
		;;
	esac
done

trap 'kill $!' USR1
trap 'kill $!; RELOAD_WALL=y' USR2
trap 'kill $!' EXIT

wallpapers=$(find "${WALLPAPER_DIR}" -type f -printf '%P\n' | shuf --random-source=/dev/urandom)
while [ -z "${wallpapers}" ]; do
	sleep 5
	wallpapers=$(find "${WALLPAPER_DIR}" -type f -printf '%P\n' | shuf --random-source=/dev/urandom)
done

if [ -n "${FIRST_WALLPAPER}" ]; then
	xwallpaper --zoom "${FIRST_WALLPAPER}"
	sleep 300 &
	wait $!
fi

while :; do
	for wallpaper in ${wallpapers}; do
		xwallpaper --zoom "${WALLPAPER_DIR}/${wallpaper}"
		sleep 300 &
		wait $!
		if [ "${RELOAD_WALL}" = "y" ]; then
			unset RELOAD_WALL
			break
		fi
	done
	wallpapers=$(find "${WALLPAPER_DIR}" -type f -printf '%P\n' | shuf --random-source=/dev/urandom)
done
