#!/bin/sh
# shellcheck disable=SC2154
export DISPLAY=:0

. "${HOME}/.config/env"

xset +fp "${HOME}/.local/share/fonts/"
xset fp rehash

"${HOME}/.config/X11/dyn-wallpapers" -s "${WALLPAPER_DIR}/landscape.jpg" &
"${HOME}/.config/X11/dyn-status" &
"${HOME}/.config/X11/monitors"

xwallpaper --zoom "${WALLPAPER_DIR}/landscape.jpg"

compton &

(
	sleep 3
	xmodmap "${HOME}/.config/X11/xmodmap"
) &

if id -u dev >/dev/null 2>&1; then
	xhost +SI:localuser:dev
fi

if id -u steam >/dev/null 2>&1; then
	xhost +SI:localuser:steam
fi

xrdb -merge ~/.config/X11/xresources

exec dwm
